FROM debian:stable-slim
WORKDIR /app/
ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1
ENV TELEGRAM_TOKEN=
ENV VKONTAKTE_TOKEN=
ADD . .
RUN apt-get update
RUN apt-get -y --no-install-recommends install python3-minimal python3-pip python3-setuptools python3-multidict python3-requests python3-yarl
RUN apt-get clean
RUN rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/* /usr/share/doc/*
RUN python3 -m pip install --no-cache-dir -r requirements.txt
CMD [ "python3", "app.py" ]
